#transcriptome 
transcriptome: /data/comocn/card_spatialtranscriptomics/refdata-gex-GRCh38-2020-A
#probeset
probeset: /data/comocn/card_spatialtranscriptomics/refdata-gex-GRCh38-2020-A/probesets/10x_probeset_v1.0.csv

metadata: /data/comocn/card_spatialtranscriptomics/metadata.csv